name: Debian Check
on: workflow_call

jobs:
  Check-Version-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: 'debian/changelog'
      - name: Check Version
        id: check-version
        if: steps.changed-files.outputs.all_changed_files
        env:
          repository: ${{ github.repository }}
        run: |
          result=$(echo ${repository} | grep "/" || true)
          project_tmp=${repository}
          if [[ "$result" != "" ]]; then
              project_tmp=$(echo ${repository} | awk -F'/' '{print $2}' || true)
          fi
          version_str=$(dpkg-parsechangelog -l debian/changelog -n 2|grep ${project_tmp}|awk -F'[()]' '{print $2}'|grep -v '^$\|^Task\|^Bug\|^Influence'|tr '\n' ' '|| true)
          version_num=$(echo $version_str|awk '{print NF}' || true)
          echo "version_str is ${version_str}"
          echo "version_num is ${version_num}"
          if [[ "$version_num" == "2" ]]; then
              version0=$(echo $version_str|awk '{print $1}' || true)
              version1=$(echo $version_str|awk '{print $2}' || true)
              check_result=$(dpkg --compare-versions ${version0} gt ${version1} && echo true || echo false)
          fi
          echo "check_result=$check_result" >> $GITHUB_OUTPUT
          echo "version_str=$version_str" >> $GITHUB_OUTPUT
      - name: Comment PR
        if: steps.check-version.outputs.check_result == 'false'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            检测到debian/changelog版本变动异常: ${{steps.check-version.outputs.version_str}}
      - if: steps.check-version.outputs.check_result == 'false'
        run: |
          if [[ "$check_result" == "false" ]];then
            echo "debian/changelog版本变动异常:$version_str"
            exit 1
          fi
        env:
          check_result: ${{ steps.check-version.outputs.check_result }}
          version_str: ${{ steps.check-version.outputs.version_str }}
