name: Debian Check
on: workflow_call

jobs:
  Check-Env-Set-Words:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.GITHUB_TOKEN }}","X-GitHub-Api-Version": "2022-11-28","Accept": "application/vnd.github+json"} }'
      - uses: actions/checkout@v4
        with:
          repository: kuchune/check-tools
          ref: develop
          sparse-checkout: debianCheck/do-with-data.py
          sparse-checkout-cone-mode: false
          path: debianCheck
      - id: check-env-keys
        run: 
          check_result=$(python3 debianCheck/debianCheck/do-with-data.py ${check_type} ${check_keys} fetch-api-data-action/data.json)
          echo "check_result=$check_result" >> $GITHUB_OUTPUT
        env:
          check_type: all
          check_keys: export,unset
      - name: Publish reports
        id: artifact-upload-step
        if: steps.check-env-keys.outputs.check_result != '{}'
        uses: actions/upload-artifact@v4
        with:
          name: env-set-words-check-report
          path: result.json
      - name: Comment PR
        if: steps.check-env-keys.outputs.check_result != '{}'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            检测到export/unset敏感词变动:https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}/artifacts/${{steps.artifact-upload-step.outputs.artifact-id}}
      - run: |
          if [[ "$check_result" != "{}" ]];then
            echo "环境设置敏感词export/unset检查不通过"
            exit 1
          fi
        env:
          check_result: ${{ steps.check-env-keys.outputs.check_result }}